beans_tokens = {
    "account_data": {
        "email": "somad.nachirou@ai.trellix.io",
        "first_name": "NACHIROU",
        "last_name": "Somad",
    },
    "new_account_data": {
        "first_name": "Somad",
        "last_name": "NACHIROU",
    },
    "credit_data": {
        "account": "somad.nachirou@ai.trellix.io",
        "rule": "rule:liana:api_credit",
        "quantity": 30,
        "description": "Customer rewarded for his first connection ",
        "uid": "first_1",
    },
    "credit_canceled_data": {
        "id": "cr_0qmq1i5f3rom7w2qmtp67o6nhlwagb3w",
        "object": "credit",
        "beans": 30,
        "account": "acc_0ueqlqh9npn35v",
        "rule": "rule_0fo6ofiv",
        "description": "Customer rewarded for his first connection ",
        "status": "committed",
        "uid": "first_1",
        "failure_code": None,
        "failure_message": None,
        "created": "2024-03-01T15:37:17.316441Z",
        "updated": "2024-03-01T15:37:17.316461Z",
    },
    "debit_data": {
        "account": "somad.nachirou@ai.trellix.io",
        "rule": "rule_0fo6ofiv",
        "quantity": 12,
        "description": "Debited for a $12 discount on order #12345.",
        "uid": "order_12345_debit",
    },
    "debit_canceled_data": {
        "id": "dr_05pfx3hfidmooctu8tafgynbaul4pd6u",
        "object": "debit",
        "beans": 12,
        "account": "acc_0ueqlqh9npn35v",
        "rule": "rule_0fo6ofiv",
        "description": "Debited for a $12 discount on order #12345.",
        "status": "committed",
        "failure_code": None,
        "failure_message": None,
        "uid": "order_12345_debit",
        "created": "2024-03-05T10:47:35.646271Z",
        "updated": "2024-03-05T10:47:35.646290Z",
    },
    "rule_data": {
        "uid": "rule:liana:new_beans_card",
    },
    "new_rule_data": {
        "settings": {
            "drcr": "credit",
            "beans": 300,
            "title": "Review a product",
            "statement": "Write a product review and get 300 points",
            "help_text": "You will receive your credit after each product review.",
            "position": 5,
        },
    },
    "rule_type_data":{
        "uid": "rule:liana:new_beans_card",
        "title": "Register",
        "statement": "Join our rewards program and get x points",
        "is_active": True,
        "settings": {
            "drcr": {
                'type': 'choice', 
                'label': 'Transaction type', 
                'hidden': True, 
                'choices': [['credit', 'credit']], 
                'default': 'credit', 
                'help_text': 'Whether this rule triggers a credit or debit transaction.',
            },
            "beans": {
                'type': 'integer', 
                'label': 'Points', 
                'default': 300, 
                'help_text': 'The number of points to award to shoppers when they complete the action.',
            },
            "title": {
                'type': 'text', 
                'label': 'Title', 
                'default': 'Register', 
                'help_text': 'Rule title (used for translation)',
            },
            "statement": {
                'type': 'text', 
                'label': 'Statement', 
                'default': 'Join our rewards program and get [beans]', 
                'help_text': 'A statement describing the rule to shoppers.',
            },
            "help_text": {
                'type': 'text', 
                'label': 'Help Text', 
                'default': 'Join now to receive your credit', 
                'help_text': 'Let customers know how to perform the action to earn points',
            },
            "position": {
                'type': 'integer', 
                'label': 'Position', 
                'default': 1, 
                'help_text': 'The position of the rule when listing the rules on the rewards program page.',
            },
        },
    },
}
